### ISSUE TITLE
[Enhancement] Example of Using Semaphores or Mutex within a ThreadClass

### ISSUE THREAD

**Issue by MSKrakower** [sdckey/EnScript-Samples#10]
Could you provide a simple of example of using threads to iterate over a list of entries, either by using SemaphoreClass or MutexClass to manage deployment across the threads?

**Comment by sdckey** [comment]
I'm afraid that I have little experience of multithreaded processing. I used it once and only needed the **synchonized** keyword; I did not use SemaphoreClass or MutexClass.

The best advice I can give you is to review the ThreadClass examples in the EnScript help file.
