### ISSUE TITLE
Question about order using Parse Method

### ISSUE THREAD

**Issue by FMS1989** [sdckey/EnScript-Samples#11]
Hello,

I hope this message finds you well! I was trying to use the parse method from the NameListClass, and I was wondering if you could provide some insight if you have time. 

I tried using Extension.Parse("Lx01,L01", ","); and it compiled fine but would not recognize the image files. When I reversed it, Extension.Parse("L01,Lx01", ","); it recognized my image files and loaded then into my encase. Do you know why reversing the order makes a difference?

Any advice would be appreciated!

Thank you!

**Comment by sdckey** [comment]
The order of child items created using the `NameListClass::Parse()` method should make no difference when using the `NodeClass::Find()` method.

That said, it's difficult to be sure without seeing the rest of your code.
