### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Rasmus-Riis** [sdckey/EnScript-Samples#14]
Is there any way that you could release the source code to the EnScript 'Windows Drive Letter Assignments' [https://support.guidancesoftware.com/forum/downloads.php?do=file&id=1338 ](url)?

I have built a 'startup script' that - among other things - does the same. -but I simply cannot get it to catch if there are 2 drive letters on a GUID partitioned harddisk.

Regards,

**Comment by sdckey** [comment]
Hi Rasmus,

Good to hear from you.

Please email at skey[at]opentext.com and I will send you the script by return.

Best.
