### ISSUE TITLE
Results Sets to LEF example

### ISSUE THREAD

**Issue by AlexHarrison90** [sdckey/EnScript-Samples#2]
Hi Simon, firstly, thank you so much for taking the time to write these examples and share them!

I'm trying to work with results sets and can create and populate them using code based on your example. I also want the same script to be able to export the result set contents to a LEF, but the first time I run the script, nothing gets exported once the Results Sets are created and populated. If I immediately re-run the script (i.e. the results sets already exist) then the export completes successfully. I'm thinking this is an issue with the result set not updating quickly enough, or the script needing to refresh it, but if you could shed some light on this or provide a working example that would be very much appreciated.

Many thanks,
Alex

**Comment by AlexHarrison90** [comment]
PS I tried to assign an enhancement label, but don't appear to have permission :(

**Comment by sdckey** [comment]
I think what you're saying is that you're trying to create a result-set and use its contents in the same script?

I'm not in a position to check at the moment, but I'm 95% certain that the result-set isn't finalised till the script finishes running. There are a couple of process that work like this in EnCase.

There are a couple of alternative options that spring to mind:

- Add each item to the result-set and export it to the same time.
- Obtain each item's moniker and store it in a list or SQLite database. You can then use ItemCacheClass to resolve the moniker back to the item. Be warned that this is slow.
