### ISSUE TITLE
BuiltIn Image

### ISSUE THREAD

**Issue by thiagotankian** [sdckey/EnScript-Samples#4]
Hi Simon,
Thanks for sharing all of these scripts, it is being very usefull for undertanding the enscript programming structure.
Is there a way to include a builtIn image to an enscript? I tried different options, using the DialogClass with the ImageWindowsClass, but with no luck.
I appreciate if you could help
Regards,

**Comment by sdckey** [comment]
I've added an example to the following folder:

- https://github.com/sdckey/EnScript-Samples/tree/master/05%20-%20Dialog%20Boxes/Example%20Dialog%20With%20Logo

**Comment by thiagotankian** [comment]
OMG I can't believe that it was so simple!! Thanks a lot for help me with that, and also th share these examples with the community.
Best,
