### ISSUE TITLE
Processed evidences / ITEMCLASS get  value

### ISSUE THREAD

**Issue by thiagotankian** [sdckey/EnScript-Samples#5]
Hi Simon, I'm being work in some customs to my EnScript and after some tests and researches I would like your help just to understand if what I am wondering to do is possible or not. 
Is there a way to get the content related to a processed evidence? For example, I processed an evidence with a particular options selected (for example index, system info parser and etc) and I would like to check which evidences were processed using this custom label and the status of the processing (completed / failed) - these information are in the "Status" and "Option" fields in the Processor Manager tab.
The other questions is related to the ITEMCLASS class. I'm trying to export the Categories from an evidence to a text file, but if I only use the method entryclass.category() it will return the category number and not the value (as it has a Category type). I tried to declare a "support" variable ITEMCLASS:Category in order to help me to get the Category name, but I am probably missing something easy here.
I will appreciate if you could help me to undertand where I am doing something wrong.
Regards,

**Comment by alexharrison-ot** [comment]
+1 I'm also trying and failing to get the category from the itemclass but can't work out how to get the category name rather than just the category value

**Comment by sdckey** [comment]
> Is there a way to get the content related to a processed evidence? For example, I processed an evidence with a particular options selected (for example index, system info parser and etc) and I would like to check which evidences were processed using this custom label and the status of the processing (completed / failed) - these information are in the "Status" and "Option" fields in the Processor Manager tab.

You can use `EvidenceClass::ProcessingStatus()` to to get the processing status of each evidence item in your case. There isn't, as far as I know, any way of obtaining additional processing information, at least not from the item itself.

> The other questions is related to the ITEMCLASS class. I'm trying to export the Categories from an evidence to a text file, but if I only use the method entryclass.category() it will return the category number and not the value (as it has a Category type). I tried to declare a "support" variable ITEMCLASS:Category in order to help me to get the Category name, but I am probably missing something easy here.

Every enumeration inherits `EnumClass::SourceText()` and `EnumClass::DisplayText()`. So `EntryClass::Categories::SourceText(12)` will return "DOCUMENT_SPREADSHEET"; `EntryClass::Categories::DisplayText(12)` will return "Document - Spreadsheet".

**Comment by thiagotankian** [comment]
Thank you Simon!! I was able to get the category name.

As my case already have the evidence, I didn’t find a method using EvidenceClass in order the get this information, and not add a new evidence (as the examples that we have in the Enscript help). I’ll keep trying to do that, but I’ll appreciate if you have any other idea.

Best

**Comment by sdckey** [comment]
Each case has a property called EvidenceRoot(), which is the root object in a list of EvidenceClass objects you can iterate. 

For example, if your case is _c_, you can do the following:

`foreach (EvidenceClass e in c.EvidenceRoot()) {Console.WriteLine(e.ProcessingStatus());}`

**Comment by thiagotankian** [comment]
Hi Simon, that makes sense! I tried and it worked very well! Thanks again for your support!!!
