### ISSUE TITLE
Question about Function in EnCase 

### ISSUE THREAD

**Issue by FMS1989** [sdckey/EnScript-Samples#8]
Hello,

I am reading a suggested reading you posted called "DFIR445 EnScript Fundamentals". I must admit I find this document very helpful so far! I am a little confused on pages 3-36 to 3-37 going over Functions in EnScript. I noticed in the image below it lays out the function and what it will accomplish. I understand what each line is accomplishing

![image](https://user-images.githubusercontent.com/70933393/93157880-15111a80-f6d9-11ea-9d59-69aaee79a118.png)

When I go to the next page it says the function is complete and that we can pretty much ignore it now unless you need to edit it.

![image](https://user-images.githubusercontent.com/70933393/93158009-56092f00-f6d9-11ea-9367-aa16dc623144.png)

but I no longer see the code for it? I see the function being called on line 23 but how does this script know what the function is suppose to do if the code is no longer visible?  I understand that ValidateMFTRecordSizes() is the new function that was created but how does the script know what that function does if the code is removed? Is it added or stored somewhere else that I just can't see?

Thanks!

[DFIR445-EnScript Fundamentals Version 8-01pi (03-01-2019).pdf](https://github.com/sdckey/EnScript-Samples/files/5222126/DFIR445-EnScript.Fundamentals.Version.8-01pi.03-01-2019.pdf)

**Comment by sdckey** [comment]
It's a partial screenshot. The `ValidateMFTRecordSizes()` function still exists below.

**Comment by FMS1989** [comment]
Ah so it's not at the top of the script? I figured you would have to have it before the actual function is being used. I did notice on the next couple of pages the screenshots don't have the code so is it best practice to move it all the way to the bottom of the script?

**Comment by sdckey** [comment]
It's entirely your choice - functions can be declared in any order.

**Comment by FMS1989** [comment]
Interesting! Noted - thank you!
