### ISSUE TITLE
Question about EnScript Help in EnCase

### ISSUE THREAD

**Issue by FMS1989** [sdckey/EnScript-Samples#9]
Hello,

Would you be able to recommend a book that goes over the EnScript language (besides the two documentations that guidance software provides)? 

Would you be able to provide any professional advice as far as the EnScript help page/Class browser? I find it confusing and a little daunting to understand at first initial glance.

Thank you!

**Comment by sdckey** [comment]
There are no EnScript books that I know of.

The only advice I can give you regarding the class browser is to compare the definitions of the classes/functions it contains to sample code in this repository and elsewhere.

Also, be aware that any property 'getter' functions that have a boolean value of `true` in the **Set** column will have an associated 'setter' function. For example, if there is a function called `Comment()` marked as **Set**, there will also be a `SetComment()` method.

**Comment by FMS1989** [comment]
Ok - thank you! I will try to approch the understanding the help emtho by comparing existing scripts.
